version: '3.8'

services:
  web:
    build: .
    container_name: infoparkir_web
    ports:
      # Port 8989 diakses dari VPS/Host, 80 diakses di dalam container Apache
      - "8989:80"
    volumes:
      # Menghubungkan folder host ke dalam container
      - .:/var/www/html
    extra_hosts:
      # Akses database MySQL native di VPS melalui host.docker.internal
      - "host.docker.internal:host-gateway"
    environment:
      - CI_ENV=production
      # Konfigurasi Database MySQL
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=infoparkir
    restart: unless-stopped
